### PR TITLE
Sprint 37

### PR DESCRIPTION
**Pull request by rahulparekh**

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@WesCoomber just a heads up it looks like Github is currently not able to link your commits to your Github account ([example, see the ? mark at the top](https://github.com/IMOD-ASU/imod/commit/a181bb9d778ce88074c742401c7dfef8c25d0d15)).
If you want those to be linked, please make sure your email is set on your local git instance.
https://help.github.com/articles/setting-your-email-in-git/

**Comment by WesCoomber** [comment]
thanks, I took a look at I think its fixed.

Wesley

**Comment by WesCoomber** [comment]
**and I think its fixed*

**Comment by ChristianMurphy** [comment]
@WesCoomber yup its fixed :+1:

**Pull request merged**
